spring:
  application:
    name: neure-config
  cloud:
    config:
#      discovery:
#        enabled: true
#        service-id: neure-configserver
      server:
        git:
          uri: https://github.com/plujezi/config-repo.git
server:
  port: 9020


