
server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    instance-id: http://localhost:9010
spring:
  application:
    name: reigister-name
